<?php
$html = array();
$html[] ='<ul class="nav navbar-nav">';

foreach ($this->container as $page) {
	  /* @var $page Zend_Navigation_Page */
		
    $isActive = FALSE;
    $htmlSub = array();

    if (!$page->isVisible() || !$this->navigation()->menu()->accept($page)) {
        continue;
    }
    
    $isActive = $page->isActive(true);
    if($dropdown = !empty($page->pages)){
        foreach ($page->pages as $subpage) {
            
            if (!$subpage->isVisible() || !$this->navigation()->menu()->accept($subpage)) {
                continue;
            }

            if ($subpage->get('divider') == TRUE) {
                $htmlSub[] = '<li class="divider"></li>';
                continue;
            }
            
            
            $class = $subpage->getClass();
            $htmlSub[] = '<li' . ($subpage->isActive() ? ' class="active"' : '') . '>';
            $htmlSub[] = '<a href="' . $subpage->getHref() . '" class="'. $class .'">';

            if ($subpage->get('icon')) {
                $htmlSub[] = '<i class="fa fa-' . $subpage->get('icon') . '"></i>';
            }

            $htmlSub[] = $subpage->getLabel();
            $htmlSub[] = "</a>";
            $htmlSub[] = "</li>";
        }
    }

    $class = $page->getClass();
    if(!empty($htmlSub) && $dropdown){
        $html[] = '<li class="dropdown' . ($isActive ? ' active' : '') . '" >';
        $class = trim('dropdown-toggle ' . $class);
        $html[] = '<a href="' . $page->getHref() . '" class="'. $class .'" data-toggle="dropdown">';
        if ($page->get('icon')) {
        	$html[] = '<i class="fa fa-' . $page->get('icon') . '"></i>';
        }
        $html[] = $page->getLabel();
        $html[] = '<b class="caret"></b>';
        $html[] = '</a>';
        $html[] = '<ul class="dropdown-menu">';
        $html[] = join(PHP_EOL, $htmlSub);
        $html[] = '</ul>';
        $html[] = '</li>';
    }else{
        $html[] = '<li' . ($isActive ? ' class="active"' : '') . '>';
        $html[] = '<a href="' . $page->getHref() .'" class="'. $class .'">';
        if ($page->get('icon')) {
            $html[] = '<i class="fa fa-' . $page->get('icon') . '"></i>';
        }
        $html[] = $page->getLabel();
        $html[] = '</a>';
        $html[] = '</li>';
    }
}

$html[] = '</ul>';
echo join(PHP_EOL, $html);